spring:
  datasource:
    #    driver-class-name: com.mysql.jdbc.Driver
    #    url: jdbc:h2:mem:localhost;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:mysql://127.0.0.1:3306/learning_spring_batch
    username: root
    password: zumbox123
    schema: classpath:/org/springframework/batch/core/schema-mysql.sql
  batch:
    initialize-schema: always
